### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ktsn** [ktsn/template-vue#1]
- [x] build scripts
- [x] examples of testing
- ~~preprocessors~~
- [x] postcss
- [x] README for usage
- [x] use unassert
- styles
  - [x] reset
  - [x] styles for example component
